#cloud-config

users:
  - name: "festiz"
    groups:
      - "sudo"
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCl1FcATiFSzsQBaXXd7zetJfSOAW85Wx3CVyuY6mOuw4ZNdTH8s1P3U//18pZE1xa0E073crwsy51/vuMH77VQdmkySQ8EFEJ9dIS5NX9iJ9s+m4tlKFC/CQJP0ao14KvQTIPQy2Dxku4N4H5nex5MXYxIpd8TJjV9HPlTL5Tf1hd/6zhq1OkFw/Fbt7Nkvy7CEFvtXpQDlVOxUUvqGeIFL4MnmofuJtkkV7jE9X2EohnnDP9nIye2n1Avsdw1n+u/T1fQYiyb7blsSFPOR37aFalFyd0s/38KeFhIME3y8p6CCw1ap6W8hIMqEI2ze1m22GXi1uk9+Hrqk8KvlwHt festiz@Stefan-Wallins-MBP.local"
hostname: "coreos_001"
coreos:
  etcd:
    name: "coreos_001"
write_files:
  - path: "/etc/resolv.conf"
    permissions: "0644"
    owner: "root"
    content: |
      nameserver 8.8.8.8
      nameserver 8.8.4.4
